# Generated by Django 6.0.6 on 2026-06-30 21:19

import django.db.models.deletion
import hopehub.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernanceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_type', models.CharField(choices=[('HIPAA_SECURITY', 'HIPAA Security Rule'), ('42_CFR_PART_2', '42 CFR Part 2 (SUD Privacy)'), ('DATA_MINIMIZATION', 'Data Retention & Minimization Policy')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body_text', models.TextField(help_text='Preserves line breaks and explicit paragraph spaces.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governance Policy Section',
                'ordering': ['regulation_type'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(help_text="e.g., 'encryption_invariants'", max_length=100, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('constraint_data', models.JSONField(help_text='Valid JSON structural guidelines parsed by AI agents.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Development Constraint',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', hopehub.models.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emotion', models.CharField(choices=[('joyful', 'Joyful'), ('peaceful', 'Peaceful'), ('grateful', 'Grateful'), ('hopeful', 'Hopeful'), ('balanced', 'Balanced'), ('reflective', 'Reflective'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('frustrated', 'Frustrated'), ('angry', 'Angry'), ('tired', 'Tired'), ('overwhelmed', 'Stressed')], max_length=50)),
                ('mood_rating', models.IntegerField(choices=[(1, 'Crisis / Extremely Low'), (2, 'Very Low / Severe Distress'), (3, 'Low / Visibly Struggling'), (4, 'Mildly Low / Flat'), (5, 'Neutral / Baseline'), (6, 'Mildly Good / Stable'), (7, 'Good / Positive'), (8, 'Very Good / High Energy'), (9, 'Excellent / Vibrant'), (10, 'Peak Joy / Triumphant')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_images')),
                ('categories', models.ManyToManyField(blank=True, to='hopehub.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='hopehub.tag')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
            },
        ),
    ]
