# Generated by Django 6.0.4 on 2026-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='emotion',
            field=models.CharField(choices=[('joyful', 'Joyful'), ('peaceful', 'Peaceful'), ('grateful', 'Grateful'), ('hopeful', 'Hopeful'), ('balanced', 'Balanced'), ('reflective', 'Reflective'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('frustrated', 'Frustrated'), ('angry', 'Angry'), ('tired', 'Tired'), ('overwhelmed', 'Stressed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood_rating',
            field=models.IntegerField(choices=[(1, 'Crisis / Extremely Low'), (2, 'Very Low / Severe Distress'), (3, 'Low / Visibly Struggling'), (4, 'Mildly Low / Flat'), (5, 'Neutral / Baseline'), (6, 'Mildly Good / Stable'), (7, 'Good / Positive'), (8, 'Very Good / High Energy'), (9, 'Excellent / Vibrant'), (10, 'Peak Joy / Triumphant')]),
        ),
    ]
