# Generated by Django 6.0.4 on 2026-05-30 19:57

import hopehub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopehub', '0002_alter_journalentry_emotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_type', models.CharField(choices=[('HIPAA_SECURITY', 'HIPAA Security Rule'), ('42_CFR_PART_2', '42 CFR Part 2 (SUD Privacy)'), ('DATA_MINIMIZATION', 'Data Retention & Minimization Policy')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body_text', models.TextField(help_text='Preserves line breaks and explicit paragraph spaces.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governance Policy Section',
                'ordering': ['regulation_type'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(help_text="e.g., 'encryption_invariants'", max_length=100, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('constraint_data', models.JSONField(help_text='Valid JSON structural guidelines parsed by AI agents.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Development Constraint',
            },
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='text',
            field=hopehub.models.EncryptedTextField(),
        ),
    ]
