# Generated by Django 6.0.6 on 2026-06-30 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('persona', models.CharField(choices=[('Core Vectors', [('ENTRY_POINT', 'Entry Point / Execution Vector'), ('COMPILER_MODULE', 'Standard Codebase Module')]), ('Web Assets & Client Interface', [('UI_LAYOUT', 'UI Layout (.html)'), ('UI_STYLE', 'UI Style (.css)'), ('UI_LOGIC', 'UI Logic (.js)'), ('UI_MEDIA', 'UI Media (.jpeg, .png, etc.)')]), ('System Config & Documentation', [('DOCUMENTATION', 'Documentation (.md, .txt)'), ('CONFIGURATION', 'Configuration Registry (.ini, .yaml, .json)')]), ('Logs & Diagnostics', [('DIAGNOSTIC_LOG', 'System Execution Log (.log)')])], default='COMPILER_MODULE', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Component'), ('STAGED_FOR_DELETION', 'Quarantined / Pending Deletion Review')], default='ACTIVE', max_length=30)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public Access Node'), ('PRIVATE', 'Private Protected Node')], default='PRIVATE', max_length=10)),
                ('locked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Primary unified summary of what this component module executes.')),
                ('description_audiences', models.JSONField(blank=True, default=dict, help_text='Stores segregated documentation data blocks: developer_docs, stakeholder_docs, end_user_docs.')),
                ('created_by', models.ForeignKey(help_text='The authenticated developer who authorized the execution string.', on_delete=django.db.models.deletion.PROTECT, related_name='forged_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Component Asset Profile',
                'verbose_name_plural': 'Component Asset Profiles',
            },
        ),
        migrations.CreateModel(
            name='DeltaDirectives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directive_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('instructions', models.TextField()),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delta Directive Profile',
                'verbose_name_plural': 'Delta Directive Profiles',
            },
        ),
        migrations.CreateModel(
            name='DeltaNotesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_seconds_logged', models.PositiveIntegerField(default=0, help_text='Total accumulated active focus time recorded in seconds.')),
                ('last_started_at', models.DateTimeField(blank=True, help_text='Timestamp when the active session timer toggle was engaged.', null=True)),
                ('user', models.ForeignKey(help_text='The developer compiling this active workspace iteration note.', on_delete=django.db.models.deletion.CASCADE, related_name='delta_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delta Notes Entry',
                'verbose_name_plural': 'Delta Notes Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.CharField(choices=[('aurora', 'Aurora'), ('hopehub', 'HopeHub')], default='aurora', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_context', models.TextField(help_text='The original delta_notes that triggered this request.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Developer Review'), ('EXECUTED', 'Executed and Locked'), ('ROLLED_BACK', 'Destroyed and Rolled Back'), ('REJECTED', 'Rejected by User')], default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('macro', models.CharField(help_text='e.g., /page, /api, /bind', max_length=50)),
                ('arguments', models.JSONField(help_text='Array of string variables passed to the handler.')),
                ('affected_files', models.JSONField(default=list, help_text='List of file paths created or mutated.')),
                ('execution_order', models.PositiveIntegerField(default=0)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='aurora.workspacetransaction')),
            ],
            options={
                'ordering': ['execution_order'],
            },
        ),
    ]
