# Generated by Django 6.0.4 on 2026-06-15 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaDirectives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directive_name', models.CharField(db_index=True, help_text="The system lookup name identifying this minion (e.g., 'minion_AI_writer').", max_length=255, unique=True)),
                ('instructions', models.TextField(help_text='The absolute master system prompt directive for this model.')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text="Stores engine controls like {'model': 'llama-3.1-8b-instant', 'temperature': 0.3}")),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable or disable this minion profile.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delta Directive Profile',
                'verbose_name_plural': 'Delta Directive Profiles',
            },
        ),
        migrations.CreateModel(
            name='ComponentRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('persona', models.CharField(choices=[('Core Vectors', [('ENTRY_POINT', 'Entry Point / Execution Vector'), ('COMPILER_MODULE', 'Standard Codebase Module')]), ('Web Assets & Client Interface', [('UI_LAYOUT', 'UI Layout (.html)'), ('UI_STYLE', 'UI Style (.css)'), ('UI_LOGIC', 'UI Logic (.js)'), ('UI_MEDIA', 'UI Media (.jpeg, .png, etc.)')]), ('System Config & Documentation', [('DOCUMENTATION', 'Documentation (.md, .txt)'), ('CONFIGURATION', 'Configuration Registry (.ini, .yaml, .json)')]), ('Logs & Diagnostics', [('DIAGNOSTIC_LOG', 'System Execution Log (.log)')])], default='COMPILER_MODULE', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Component'), ('STAGED_FOR_DELETION', 'Quarantined / Pending Deletion Review')], default='ACTIVE', max_length=30)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public Access Node'), ('PRIVATE', 'Private Protected Node')], default='PRIVATE', max_length=10)),
                ('locked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Primary unified summary of what this component module executes.')),
                ('description_audiences', models.JSONField(blank=True, default=dict, help_text='Stores segregated documentation data blocks: developer_docs, stakeholder_docs, end_user_docs.')),
                ('created_by', models.ForeignKey(help_text='The authenticated developer who authorized the execution string.', on_delete=django.db.models.deletion.PROTECT, related_name='forged_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Component Asset Profile',
                'verbose_name_plural': 'Component Asset Profiles',
            },
        ),
        migrations.CreateModel(
            name='DeltaNotesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_seconds_logged', models.PositiveIntegerField(default=0, help_text='Total accumulated active focus time recorded in seconds.')),
                ('last_started_at', models.DateTimeField(blank=True, help_text='Timestamp when the active session timer toggle was engaged.', null=True)),
                ('user', models.ForeignKey(help_text='The developer compiling this active workspace iteration note.', on_delete=django.db.models.deletion.CASCADE, related_name='delta_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delta Notes Entry',
                'verbose_name_plural': 'Delta Notes Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the informational page.', max_length=255)),
                ('html_content', models.TextField(help_text='Raw HTML content for the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_registry', models.ForeignKey(help_text='The parent component registry for this static content.', on_delete=django.db.models.deletion.CASCADE, related_name='static_contents', to='aurora.componentregistry')),
            ],
        ),
    ]
