# Generated by Django 6.0.4 on 2026-06-04 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('persona', models.CharField(choices=[('ENTRY_POINT', 'Entry Point / Execution Vector'), ('COMPILER_MODULE', 'Standard Codebase Module')], default='COMPILER_MODULE', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Component'), ('STAGED_FOR_DELETION', 'Quarantined / Pending Deletion Review')], default='ACTIVE', max_length=30)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public Access Node'), ('PRIVATE', 'Private Protected Node')], default='PRIVATE', max_length=10)),
                ('locked', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('description_audiences', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Component Asset Profile',
                'verbose_name_plural': 'Component Asset Profiles',
            },
        ),
    ]
