# Generated by Django 6.0.6 on 2026-06-28 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_context', models.TextField(help_text='The original delta_notes that triggered this request.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Developer Review'), ('EXECUTED', 'Executed and Locked'), ('ROLLED_BACK', 'Destroyed and Rolled Back'), ('REJECTED', 'Rejected by User')], default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('macro', models.CharField(help_text='e.g., /page, /api, /bind', max_length=50)),
                ('arguments', models.JSONField(help_text='Array of string variables passed to the handler.')),
                ('affected_files', models.JSONField(default=list, help_text='List of file paths created or mutated.')),
                ('execution_order', models.PositiveIntegerField(default=0)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='aurora.workspacetransaction')),
            ],
            options={
                'ordering': ['execution_order'],
            },
        ),
    ]
