# Generated by Django 6.0.6 on 2026-07-02 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique workspace thread isolation tracker token.', max_length=255)),
                ('role', models.CharField(choices=[('user', 'User Input Prompt'), ('model', 'Model Assistant Response')], db_index=True, max_length=10)),
                ('text', models.TextField(help_text='Raw conversational data chunk payload.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='The authenticated user operating the active workspace session thread.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Ledger Entry',
                'verbose_name_plural': 'Chat Ledger Entries',
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='aurora_chat_ledger_idx')],
            },
        ),
    ]
