# Generated by Django 6.0.4 on 2026-05-25 17:26

import aurora.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_affected', models.CharField(choices=[('AURORA', 'Aurora Core Framework'), ('HOPEHUB', 'HopeHub UI Management'), ('CORE_LOGIC', 'Core Logic System Systems')], default='AURORA', max_length=20)),
                ('assigned_to', models.CharField(choices=[('WU', 'Wu Core Architect (70B)'), ('MINION', 'Mechanical Worker Array (8B)')], default='MINION', max_length=10)),
                ('minion_type', models.CharField(default='NONE', max_length=30, validators=[aurora.models.validate_active_minion_profile])),
                ('dense_instructions', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Human Review Gate'), ('APPROVED', 'Approved for Execution'), ('EXECUTED', 'Executed - Awaiting Acceptance'), ('ACCEPTED', 'Changes Accepted and Committed'), ('ROLLED_BACK', 'Changes Rolled Back Safely')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeltaDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive_name', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(default='BOTH', max_length=30)),
                ('dense_instructions', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_directives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeltaNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delta_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
