# Generated by Django 6.0.4 on 2026-06-05 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistry',
            name='created_by',
            field=models.ForeignKey(help_text='The authenticated developer who authorized the execution string.', on_delete=django.db.models.deletion.PROTECT, related_name='forged_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
