# Generated by Django 6.0.4 on 2026-05-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0002_deltachange_deltadirective_deltanote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedBuildStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(help_text="Unique lowercase identifier for the target feature group (e.g., 'under_construction_page').", max_length=100)),
                ('step_order', models.PositiveIntegerField(help_text='Strict sequential order for pipeline execution (e.g., 1, 2, 3, 4).')),
                ('stage', models.CharField(choices=[('SETUP_TEST', '1. Write Failing Test'), ('BUILD_HTML', '2. Generate HTML Template'), ('BUILD_VIEW', '3. Implement View Class'), ('BUILD_ROUTER', '4. Register URL Path'), ('VERIFY_TDD', '5. Run Verification Suite')], help_text='The explicit system development lifecycle phase.', max_length=20)),
                ('title', models.CharField(help_text='Short, human-readable title describing this specific automation step.', max_length=150)),
                ('target_file_path', models.CharField(help_text="Relative directory file path to modify (e.g., 'hopehub/tests/test_views.py').", max_length=255)),
                ('code_payload', models.TextField(blank=True, help_text='The raw Python code or HTML snippet text to inject or write to disk.')),
                ('anchor_signature', models.CharField(blank=True, help_text='The string or regex token used to position code insertion inside an existing file.', max_length=255)),
                ('approval_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', help_text='Controls if a worker minion has authorization to run file updates.', max_length=20)),
                ('assigned_minion', models.CharField(help_text='The descriptive identity name of the runner executing this code operation.', max_length=50)),
                ('human_notes', models.TextField(blank=True, help_text='Your personal workspace adjustments, rationale, or design notes.')),
                ('verification_command', models.CharField(help_text="The shell command run to verify compilation (e.g., 'python manage.py test').", max_length=255)),
                ('expected_exit_code', models.IntegerField(default=0, help_text='The terminal response code expected. 0 for clean pass, 1 for TDD initial failure.')),
                ('execution_logs', models.TextField(blank=True, help_text='Raw standard output and error telemetry streaming back from the active worker subprocess.')),
                ('is_executed', models.BooleanField(default=False, help_text='Tracks whether the task step has run successfully and cleared validation checkpoints.')),
            ],
            options={
                'verbose_name': 'Automated Build Step',
                'verbose_name_plural': 'Automated Build Steps',
                'ordering': ['feature_name', 'step_order'],
                'unique_together': {('feature_name', 'step_order')},
            },
        ),
    ]
