# Generated by Django 6.0.6 on 2026-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0002_rename_created_at_staticcontent_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='application',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('hopehub', 'HopeHub')], default='aurora', max_length=10),
        ),
    ]
