# Generated by Django 6.0.4 on 2026-06-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0002_alter_componentregistry_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaNotesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_seconds_logged', models.PositiveIntegerField(default=0, help_text='Total accumulated active focus time recorded in seconds.')),
                ('last_started_at', models.DateTimeField(blank=True, help_text='Timestamp when the active session timer toggle was engaged.', null=True)),
                ('user', models.ForeignKey(help_text='The developer compiling this active workspace iteration note.', on_delete=django.db.models.deletion.CASCADE, related_name='delta_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delta Notes Entry',
                'verbose_name_plural': 'Delta Notes Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
