# Generated by Django 6.0.6 on 2026-07-12 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0002_chatledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacetransaction',
            name='user',
        ),
        migrations.CreateModel(
            name='PendingCodeChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_index=True, help_text='Validated repository-relative path targeted by the proposal.', max_length=500)),
                ('original_content', models.TextField(help_text='Source content loaded when the proposal was generated.')),
                ('proposed_content', models.TextField(help_text='Replacement content returned by Wu and shown for review.')),
                ('original_sha256', models.CharField(help_text='Checksum used to detect source changes before approval.', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Developer Review'), ('APPLIED', 'Approved and Applied'), ('REJECTED', 'Rejected by Developer'), ('CONFLICT', 'Source Changed Before Approval')], db_index=True, default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_code_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Code Change',
                'verbose_name_plural': 'Pending Code Changes',
                'ordering': ['-date_created'],
            },
        ),
        migrations.DeleteModel(
            name='TrackedCommand',
        ),
        migrations.DeleteModel(
            name='WorkspaceTransaction',
        ),
    ]
