# Generated by Django 6.0.6 on 2026-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0003_remove_workspacetransaction_user_pendingcodechange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentregistry',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending Analysis'), ('COMPLETE', 'Analysis Complete'), ('FAILED', 'Analysis Failed')], default='PENDING', help_text='Current incremental documentation analysis state.', max_length=20),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='analysis_version',
            field=models.CharField(blank=True, default='', help_text='Analyzer contract version used for the stored documentation.', max_length=50),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='Most recent successful or failed AI enrichment attempt.', null=True),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='last_observed_at',
            field=models.DateTimeField(blank=True, help_text='Most recent reconciliation timestamp at which the file was observed.', null=True),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='source_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 digest from the most recently observed source content.', max_length=64),
        ),
    ]
