# Generated by Django 6.0.4 on 2026-06-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0003_deltanotesentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistry',
            name='description',
            field=models.TextField(blank=True, help_text='Primary unified summary of what this component module executes.'),
        ),
        migrations.AlterField(
            model_name='componentregistry',
            name='description_audiences',
            field=models.JSONField(blank=True, default=dict, help_text='Stores segregated documentation data blocks: developer_docs, stakeholder_docs, end_user_docs.'),
        ),
    ]
