# Generated by Django 6.0.6 on 2026-06-25 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0003_staticcontent_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deltadirectives',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deltadirectives',
            name='constraints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='deltadirectives',
            name='directive_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='deltadirectives',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deltadirectives',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
