# Generated by Django 6.0.6 on 2026-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0004_componentregistry_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentregistry',
            name='graph_sync_error',
            field=models.TextField(blank=True, default='', help_text='Most recent graph synchronization failure details.'),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='graph_sync_hash',
            field=models.CharField(blank=True, default='', help_text='Source hash most recently projected successfully into Neo4j.', max_length=64),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='graph_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending Graph Synchronization'), ('COMPLETE', 'Graph Synchronization Complete'), ('FAILED', 'Graph Synchronization Failed')], db_index=True, default='PENDING', help_text='Current PostgreSQL-to-Neo4j projection state.', max_length=20),
        ),
        migrations.AddField(
            model_name='componentregistry',
            name='graph_synced_at',
            field=models.DateTimeField(blank=True, help_text='Most recent successful Neo4j projection timestamp.', null=True),
        ),
    ]
