# Generated by Django 6.0.4 on 2026-06-14 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0004_alter_componentregistry_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaDirectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive_name', models.CharField(help_text='Name or purpose of the directive.', max_length=255)),
                ('instructions', models.TextField(help_text='Specific prompts or guidelines for the AI.')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Structured boundaries/rules for the AI.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to enable or disable these directives.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component_registry', models.ForeignKey(help_text='The parent component registry for these AI directives.', on_delete=django.db.models.deletion.CASCADE, related_name='delta_directives', to='aurora.componentregistry')),
            ],
            options={
                'verbose_name_plural': 'Delta Directives',
            },
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the informational page.', max_length=255)),
                ('html_content', models.TextField(help_text='Raw HTML content for the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_registry', models.ForeignKey(help_text='The parent component registry for this static content.', on_delete=django.db.models.deletion.CASCADE, related_name='static_contents', to='aurora.componentregistry')),
            ],
        ),
    ]
