# Generated by Django 6.0.6 on 2026-06-25 23:23
from django.db import migrations

def backfill_directive_owners(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    DeltaDirectives = apps.get_model('aurora', 'DeltaDirectives')
    
    # Fetch the first registered superuser or developer profile node
    default_user = User.objects.order_by('id').first()
    if not default_user:
        default_user = User.objects.create_superuser(
            username='system_anchor_dev',
            email='admin@aurora.local',
            password='TemporaryMigrationPass123!'
        )
        
    # Bind the owner reference to all unassigned active rows
    for directive in DeltaDirectives.objects.filter(created_by__isnull=True):
        directive.created_by = default_user
        directive.save()

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0004_deltadirectives_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_directive_owners, reverse_backfill),
    ]