# Generated by Django 6.0.4 on 2026-06-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0005_deltadirectives_staticcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistry',
            name='persona',
            field=models.CharField(choices=[('Core Vectors', [('ENTRY_POINT', 'Entry Point / Execution Vector'), ('COMPILER_MODULE', 'Standard Codebase Module')]), ('Web Assets & Client Interface', [('UI_LAYOUT', 'UI Layout (.html)'), ('UI_STYLE', 'UI Style (.css)'), ('UI_LOGIC', 'UI Logic (.js)'), ('UI_MEDIA', 'UI Media (.jpeg, .png, etc.)')]), ('System Config & Documentation', [('DOCUMENTATION', 'Documentation (.md, .txt)'), ('CONFIGURATION', 'Configuration Registry (.ini, .yaml, .json)')]), ('Logs & Diagnostics', [('DIAGNOSTIC_LOG', 'System Execution Log (.log)')])], default='COMPILER_MODULE', max_length=30),
        ),
    ]
