# Generated by Django 6.0.6 on 2026-07-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0005_componentregistry_graph_sync_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistry',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
