# Generated by Django 6.0.6 on 2026-06-25 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0005_backfill_directive_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='deltadirectives',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='deltadirectives',
            old_name='updated_at',
            new_name='date_modified',
        ),
        migrations.AlterField(
            model_name='deltadirectives',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
