# Generated by Django 6.0.6 on 2026-07-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0007_initiative_phase_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='completed',
        ),
        migrations.AddField(
            model_name='step',
            name='estimate_confidence',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Confidence in the current implementation estimate.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated implementation effort in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='validation_description',
            field=models.TextField(blank=True, help_text='Deterministic evidence required to validate this step.'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='step',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Observed validation results and supporting evidence.'),
        ),
    ]
