# Generated by Django 6.0.6 on 2026-07-24 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0009_project_step_risk_and_initiative_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='aurora.project'),
        ),
    ]
