# Generated by Django 6.0.6 on 2026-07-25 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0010_alter_initiative_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='initiative',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='initiative',
            name='assigned_to',
            field=models.ForeignKey(default='d72473bc-b25b-45d8-aaad-aed1a5416dcd', on_delete=django.db.models.deletion.PROTECT, related_name='initiatives_assigned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='assigned_to',
            field=models.ForeignKey(default='d72473bc-b25b-45d8-aaad-aed1a5416dcd', on_delete=django.db.models.deletion.PROTECT, related_name='phases_assigned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='created_by',
            field=models.ForeignKey(default='d72473bc-b25b-45d8-aaad-aed1a5416dcd', on_delete=django.db.models.deletion.PROTECT, related_name='phases_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(default='d72473bc-b25b-45d8-aaad-aed1a5416dcd', on_delete=django.db.models.deletion.PROTECT, related_name='projects_assigned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default='d72473bc-b25b-45d8-aaad-aed1a5416dcd', on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='assigned_to',
            field=models.ForeignKey(default='d72473bc-b25b-45d8-aaad-aed1a5416dcd', on_delete=django.db.models.deletion.PROTECT, related_name='steps_assigned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='created_by',
            field=models.ForeignKey(default='d72473bc-b25b-45d8-aaad-aed1a5416dcd', on_delete=django.db.models.deletion.PROTECT, related_name='steps_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this project remains available for normal engineering work.'),
        ),
        migrations.AddConstraint(
            model_name='initiative',
            constraint=models.UniqueConstraint(fields=('project', 'position'), name='unique_initiative_position_per_project'),
        ),
        migrations.AddConstraint(
            model_name='initiative',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('project', 'status'), name='unique_active_initiative_per_project'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('initiative', 'position'), name='unique_phase_position_per_initiative'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('initiative', 'status'), name='unique_active_phase_per_initiative'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='unique_active_project'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('phase', 'position'), name='unique_step_position_per_phase'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('phase', 'status'), name='unique_active_step_per_phase'),
        ),
    ]
