# Generated by Django 6.0.6 on 2026-07-28 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0011_alter_initiative_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='initiative',
            name='unique_active_initiative_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='phase',
            name='unique_active_phase_per_initiative',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_active_project',
        ),
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_active_step_per_phase',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='aurora.step'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userposition',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_positions', to='aurora.initiative'),
        ),
        migrations.AddField(
            model_name='userposition',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_positions', to='aurora.phase'),
        ),
        migrations.AddField(
            model_name='userposition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_positions', to='aurora.project'),
        ),
        migrations.AddField(
            model_name='userposition',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_positions', to='aurora.step'),
        ),
        migrations.AddField(
            model_name='userposition',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_position', to=settings.AUTH_USER_MODEL),
        ),
    ]
