# Generated by Django 6.0.6 on 2026-07-30 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0012_timeentry_userposition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_design', models.TextField(blank=True, help_text='The intended technical approach for implementing this step.')),
                ('dependencies', models.TextField(blank=True, help_text='Components, services, decisions, or prior work required by this step.')),
                ('assumptions', models.TextField(blank=True, help_text='Known assumptions that influence the implementation approach.')),
                ('implementation_notes', models.TextField(blank=True, help_text='Important observations and decisions recorded during implementation.')),
                ('discussion', models.TextField(blank=True, help_text='Planning discussion and design history relevant to this step.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='aurora.step')),
            ],
        ),
        migrations.CreateModel(
            name='StepValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Deterministic evidence required to validate this step.')),
                ('notes', models.TextField(blank=True, help_text='Observed validation results and supporting evidence.')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='aurora.step')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_validations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Repository-relative path planned for or observed during implementation.', max_length=500)),
                ('role', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTUAL', 'Actual')], db_index=True, max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why this file is expected to change or why it was modified.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='The user who recorded this file impact. Blank values may represent deterministic or automated discovery.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_files_recorded', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='aurora.step')),
            ],
            options={
                'ordering': ['role', 'file_path'],
                'constraints': [models.UniqueConstraint(fields=('step', 'file_path', 'role'), name='unique_step_file_path_per_role')],
            },
        ),
    ]
