# Generated by Django 6.0.6 on 2026-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0014_migrate_step_validation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistry',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active Component'), ('ARCHIVED', 'Archived Component')], default='ACTIVE', max_length=30),
        ),
    ]
