# Generated by Django 6.0.6 on 2026-08-12 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0015_alter_componentregistry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated developer responsible for manual registration. Null indicates repository-discovered system registration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forged_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
