# Generated by Django 6.0.6 on 2026-08-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0017_engineeringsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Developer who completed this Step. Historical attribution is independent of current Phase assignment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_steps', to=settings.AUTH_USER_MODEL),
        ),
    ]
