# Generated by Django 6.0.6 on 2026-08-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0018_step_completed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeSourceDeltaNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delta_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_initiatives', to='aurora.deltanotesentry')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_delta_notes', to='aurora.initiative')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('initiative', 'delta_note'), name='unique_initiative_source_delta_note')],
            },
        ),
    ]
