# Generated by Django 6.0.6 on 2026-08-23 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0019_initiativesourcedeltanote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HanselTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUFFICIENT', 'Sufficient Authority'), ('INCOMPLETE', 'Incomplete'), ('BROKEN', 'Broken Trail'), ('REDISCOVERED', 'Required Rediscovery')], default='IN_PROGRESS', max_length=32)),
                ('entry_authority', models.CharField(default='aurora/subsystems/hansel/contracts/HANSEL.md', max_length=500)),
                ('sufficient_authority', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hansel_trails', to='aurora.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hansel_trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
