# Generated by Django 6.0.6 on 2026-08-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0020_hanseltrail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanseltrail',
            name='sufficient_authority',
        ),
        migrations.CreateModel(
            name='HanselTrailAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_path', models.CharField(max_length=500)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='aurora.hanseltrail')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('trail', 'authority_path'), name='unique_hansel_trail_authority')],
            },
        ),
    ]
