# Generated by Django 6.0.6 on 2026-08-23 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0021_remove_hanseltrail_sufficient_authority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativePostMortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Concise retrospective summary of the completed Initiative.')),
                ('successes', models.TextField(blank=True, help_text='Approaches, decisions, or workflow behavior worth preserving.')),
                ('friction', models.TextField(blank=True, help_text='Observed problems, inefficiencies, surprises, or failed assumptions encountered during execution.')),
                ('planning_improvements', models.TextField(blank=True, help_text='Durable improvements suggested for Planning contracts, estimation, lifecycle behavior, or execution workflow.')),
                ('hansel_improvements', models.TextField(blank=True, help_text='Durable improvements suggested for Hansel routing, authority discovery, validation, or reconciliation.')),
                ('follow_up', models.TextField(blank=True, help_text='Concrete improvement work that should be considered after Initiative closeout.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_mortem', to='aurora.initiative')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiative_post_mortems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
