# Generated by Django 6.0.6 on 2026-08-31 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0022_initiativepostmortem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BROKEN_HANSEL_TRAIL', 'Broken Hansel Trail'), ('DEAD_END', 'Dead End'), ('NEEDED_SOLUTION', 'Needed Solution'), ('INEFFICIENT_NAVIGATION', 'Inefficient Navigation'), ('AUTHORITY_CONFLICT', 'Authority Conflict'), ('BOUNDARY_VIOLATION', 'Boundary Violation'), ('VALIDATION_GAP', 'Validation Gap')], db_index=True, max_length=40)),
                ('blocking_classification', models.CharField(choices=[('BLOCKING', 'Blocking'), ('NON_BLOCKING', 'Non-blocking')], db_index=True, max_length=20)),
                ('resolution_state', models.CharField(choices=[('UNRESOLVED', 'Unresolved'), ('RESOLVED', 'Resolved')], db_index=True, default='UNRESOLVED', max_length=20)),
                ('observed_condition', models.TextField(help_text='Concrete engineering problem that was encountered.')),
                ('evidence', models.TextField(blank=True, help_text='Concrete repository or execution evidence supporting the finding. May be blank when deterministic reproduction steps are sufficient.')),
                ('steps_to_reproduce', models.TextField(blank=True, help_text='Deterministic procedure that reproduces or exposes the observed condition, when applicable.')),
                ('resolution_evidence', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discovered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_findings_discovered', to=settings.AUTH_USER_MODEL)),
                ('originating_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engineering_findings', to='aurora.step')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
