# Generated by Django 6.0.6 on 2026-08-31 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0023_engineeringfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringfinding',
            name='remedial_phase',
            field=models.ForeignKey(blank=True, help_text='Planning Phase created to resolve this BLOCKING finding, when routed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engineering_findings_remediated', to='aurora.phase'),
        ),
    ]
