# Generated by Django 6.0.6 on 2026-09-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0026_reconcile_pending_engineering_findings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepRepositoryBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict, help_text='Repository-relative eligible file paths mapped to deterministic SHA-256 hashes at the start of the current execution segment.')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_repository_baselines_opened', to=settings.AUTH_USER_MODEL)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository_baseline', to='aurora.step')),
            ],
        ),
    ]
