"""
Django settings for core_logic project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import environ
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

env = environ.Env()
# Reads the local .env file if it exists, but falls back gracefully in production containers
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Now Django reads environment variables seamlessly:
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Temporarily allow everything to clear the connection path

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'crispy_forms',
    'crispy_bootstrap5',
    'hopehub',
    'aurora',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_logic.urls'

# ==============================================================================
# CRISPY FORMS FOR BOOTSTRAP 5 LAYOUT DESIGN
# ==============================================================================
# Enforces native utility wrappers compatible with global Bootswatch skins.
# ==============================================================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
# The newer version of crispy looks for a dictionary configuration:
CRISPY_CONFIG = {
    "template_pack": "bootstrap5",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Cleaned up legacy path
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_logic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'neondb'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Open your_project_name/settings.py

# Set your local layout presentation timezone
TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://djangoproject.com

# The URL prefix used when serving static files
STATIC_URL = 'static/'

# Where Django looks for additional static files during development
STATICFILES_DIRS = [ 
    BASE_DIR / 'static',  # <-- ADD THIS: Points to your new shared root static folder
]

# The absolute path where collectstatic will collect files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Absolute filesystem path to the directory that will hold user-uploaded files
MEDIA_ROOT = BASE_DIR / 'media'

# URL that handles the media served from MEDIA_ROOT
MEDIA_URL = 'media/'

# settings.py

# Force cookies to strictly respect subpath boundaries
CSRF_COOKIE_PATH = '/'
SESSION_COOKIE_PATH = '/'

# Enable strict origin tracking to prevent cross-app interference on localhost
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
# settings.py (Production Security Overhaul)

# Mitigate Cross-Site Request Forgery risks globally
# 'Lax' allows standard navigation while strictly protecting state-changing POST forms
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

