# ======================================================================
# FILE: core_logic/settings.py (PATCH 1 OF 3)
# START: ENVIRONMENT INITIALIZATION & APP MANIFEST REGISTER
# ======================================================================
"""
Django settings for core_logic project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""
import environ
from pathlib import Path
import os
from neomodel import config as neomodel_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# Reads the local .env file if it exists, but falls back gracefully in production containers
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Now Django reads environment variables seamlessly:
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Temporarily allow everything to clear the connection path

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_neomodel',  # <-- ADDED: Third-party graph extension
    'hopehub',
    'aurora',
]
# ======================================================================
# END: ENVIRONMENT INITIALIZATION & APP MANIFEST REGISTER
# ======================================================================

# ======================================================================
# FILE: core_logic/settings.py (PATCH 2 OF 3)
# START: MIDDLEWARE PIPELINES, CRISPY UI CONFS, & TEMPLATE LOOPS
# ======================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_logic.urls'

# ==============================================================================
# CRISPY FORMS FOR BOOTSTRAP 5 LAYOUT DESIGN
# ==============================================================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_CONFIG = {
    "template_pack": "bootstrap5",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_logic.wsgi.application'
# ======================================================================
# END: MIDDLEWARE PIPELINES, CRISPY UI CONFS, & TEMPLATE LOOPS
# ======================================================================

# ======================================================================
# FILE: core_logic/settings.py (PATCH 3 OF 3)
# START: DATA STORES, NEO4J LOOPBACK, COOKIE & STATIC PATH PARAMS
# ======================================================================
# Databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# ==============================================================================
# GRAPH DATABASE CONFIGURATION (NEO4J TANDEM LAYER)
# ==============================================================================
# Satisfies the library parser format while leveraging your auth-free container
neomodel_config.DATABASE_URL = 'bolt://a:a@localhost:7687'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Los_Angeles'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

# Secure Cookie Infrastructure Parameters
CSRF_COOKIE_PATH = '/'
SESSION_COOKIE_PATH = '/'
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
# ======================================================================
# END: DATA STORES, NEO4J LOOPBACK, COOKIE & STATIC PATH PARAMS
# ======================================================================
